# permissions for end users to edit machinestates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: machinestate-editor-role
rules:
- apiGroups:
  - bmc.tinkerbell.org
  resources:
  - machinestates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bmc.tinkerbell.org
  resources:
  - machinestates/status
  verbs:
  - get
