# permissions for end users to view machinestates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: machinestate-viewer-role
rules:
- apiGroups:
  - bmc.tinkerbell.org
  resources:
  - machinestates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bmc.tinkerbell.org
  resources:
  - machinestates/status
  verbs:
  - get
